version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - mynetwork

  php:
    build: ./php
    container_name: php
    ports:
      - "8082:80"
    volumes:
      - ./www:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - mynetwork
    working_dir: /var/www/html

  mysql:
    image: mysql:8.3
    container_name: mysql
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_database
      MYSQL_USER: myUser
      MYSQL_PASSWORD: password
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    command: --sql-mode=""  # Vô hiệu hóa STRICT_TRANS_TABLES & ONLY_FULL_GROUP_BY
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    build: ./phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root      
    ports:
      - "8083:80"
    depends_on:
      - mysql
    networks:
      - mynetwork

volumes:
  dbdata:

networks:
  mynetwork:
