FROM php:8.2-fpm

# Cài đặt các extension cần thiết cho Yii2
RUN docker-php-ext-install pdo pdo_mysql mysqli
RUN apt-get update && apt-get install -y \
    unzip \
    p7zip-full \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    libpng-dev \
    libzip-dev \
    zip \
    && docker-php-ext-install gd zip
# Cập nhật cấu hình PHP
RUN echo "post_max_size = 2024M" >> /usr/local/etc/php/php.ini
RUN echo "upload_max_filesize = 2024M" >> /usr/local/etc/php/php.ini

# Cài đặt Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html
